### PR TITLE
0.3.0 prepared

### PR DESCRIPTION
**Pull request by RobTillaart**

### CODE REVIEW

**Comment by RobTillaart** [comment]
@imk2021
Do you have time to give this develop branch a test run?

**Comment by imk2021** [comment]
Hello Rob

The @imk2021 didn't seem to take me to a link with code so i am guessing 
you mean test 0.3.0 development at 
https://github.com/RobTillaart/ACS712/tree/develop ?

If this is it i'll test this evening Ian

PS Is there anything in this version that i need to modify my test rig 
for, you mentioned something about int changed to float?

**Comment by RobTillaart** [comment]
Thanks for testing tonight.

There should be no breaking change for existing sketches. (I had to patch unit tests for the floats but that is about it)
- float return types are just a bit more precise.
- midPOint functions now all return current midPoint (convenience)
- new functions
  - float mA_peak2peak() 
  - uint16_t getMinimum()  getMaximum()   for debugging purpose.
- documentation updated

The only thing that may cause problems is the midPoint which changed internally from **int** to **uint16_t**.
Found no problem so far, but absence of bugs during testing is no proof :)

If this one is merged, I start to investigate https://github.com/RobTillaart/ACS712/issues/23 
(and some other open issues, and ideas and ....)

**Comment by imk2021** [comment]
Hello Rob,

Sorry something wrong with 0.3.0 as mA_AC_sampling () returns a large 
number eg 319445 mA when connected to the ACS712 at zero current.

Test Rig changes to verify results are:
Hardware, Connected A0 to A1.

Software, Added lines of code to display ADC output of A1 and raw valve 
at A0
MaxmA = analogRead( A1 );
lcd.setCursor(0, 0);             lcd.print( "Max mA's: " ); lcd.print( 
MaxmA );

Test a.
ACS712 connected to A0 and A1 (As normal)
Output A1=513, mA_AC_sampling () output= 319445 mA

Test b.
Disconnected ACS712 form A0 and A1
Connected 10k Variable resistor between 0v and vdd (5v rail) and 
adjusted to 1/2 vdd
Connected resistor wiper to A0 and A1  (A1 Reading 511, mA_AC_sampling 
() returns 22.62mA)
---------------- This test has no ACS712 noise ---------------------

Test c
wiper of 10k Variable resistor still connected to A0 and A1
But connected ACS712 to A0 and A1 via a 10uF tantalum capacitor, thus 
injecting ACS712 noise into A0 and A1
A1 Reading is still 511, but mA_AC_sampling () output is a large 
changing values in the region of 255234  mA

Test d.
Disconnecting ACS712 from the 10uf capacitor and values are A1=511, 
mA_AC_sampling () returns 26.12mA' ish)

It seems that 0.3.0 is super sensitive to ACS712 noise.

Sorry to be bring of bad news Rob, have a good evening, Ian

**Comment by RobTillaart** [comment]
Thanks for the tests, I started to collect some hardware to build a test bench here. However some other tasks got priority. 

I still cannot explain why large values pop up orher than there is either a spike on the sensors OUT or a loose wire.  To be continued.

As always thanks for your time.

**Pull request merged**
